dist: xenial
language: c

compiler: gcc

script:
 - (cd Default && make all)
 - ./Default/test-travis

notifications:
  email:
    recipients:
      - liemle@mpire.vn
      - dole@mpire.vn
      - fastbakken@gmail.com
    on_success: always # default: change
    on_failure: change # default: always